### PR TITLE
Avoid re-calculation of face orientation

### PR DESCRIPTION
**Pull request by OrigamiDraw**
The face orientations after folding were calculated twice, first in X.V_VF_EV_EA_2_Vf (as s), then in X.V_FV_2_Ff (using function M.orientation).

- Function X.V_VF_EV_EA_2_Vf was renamed X.V_VF_EV_EA_2_Vf_Ff, and now returns Ff along Vf.
- Functions X.V_FV_2_Ff and M.orientation, now unused, were removed.

This partially addresses Issue #13.
It doesn't affect Issue #17.

It fixes another issue where CPs including straight folds that are split into two or more pieces would not fold. This was because function M.area2 in function M.orientation would return a value close to 0 with a random sign due to rounding errors.

Attached is a .cp file that caused the problem.
[Crane.cp.zip](https://github.com/origamimagiro/flat-folder/files/9211547/Crane.cp.zip)

### CODE REVIEW

**Comment by origamimagiro** [comment]
Looks great! I will add a space in the output of the pair returned for style consistency, but will merge!

**Comment by origamimagiro** [comment]
Seems like there is still another issue with degree-2 vertices between collinear lines keeping your CP from folding. The issue with such vertices is known, so we should probably open an issue.

**Comment by OrigamiDraw** [comment]
Are you sure? My crane now folds correctly and I haven't been able to find another example that would cause problem.

**Comment by origamimagiro** [comment]
Ah, you are right. I think the old code was still cached in my browser. Yes, looks like your crane now folds correctly!

**Pull request merged**
