### PR TITLE
svg invertex Y axis causes issue with faceOrders

### PR DESCRIPTION
**Pull request by robbykraft**
There is an issue that arises from the inverted Y axis in the SVG rendering, which leads to the faceOrders being incorrect in the exported FOLD state. here is a test FOLD file to demonstrate the issue. two faces separated by a valley fold. counter-clockwise winding. according to the FOLD spec, in this situation, the faceOrder between face 0 and 1 should result in a +1, no matter which face comes first in the faceOrder, both are similarly above each other's normal in the case of a valley fold.

however, flat-folder will output a -1 relationship, `[1,0,-1]`. Which, looks correct if you are inverting the Y axis in the rendering (the valley fold looks like a valley fold), but the data itself is incorrect. And, the output looks incorrect in other renderers (a valley results in a mountain fold)

I can think of a couple solutions:

- don't touch the renderer, however, when asked to export the folded state FOLD file, quickly invert index [2] of each of the faceOrders, then export.
- invert the SVG renderer (which I did in the pull request), in which the SVG is given a transform, which would make the text appear upside down, so the text is similarly given a transform.

The addition of the group element was intentional and is necessary for compatibility across all browsers. It should be possible to apply a transform to the SVG directly, it is described in the SVG 2.0 spec, but all 3 major browsers are still not consisstent. However, a transform on a group is consistent.

I tested 3 browsers (Chrome, Firefox, Safari), show text, touch interface. all of this seems to work.

```json
{
	"file_spec": 1.1,
	"file_author": "Kraft",
	"file_classes": ["singleModel"],
	"frame_attributes": ["2D"],
	"frame_title": "one fold",
	"frame_classes": ["creasePattern"],
	"vertices_coords": [[0,0],[0.6,0],[1,0],[1,1],[0.4,1],[0,1]],
	"edges_vertices": [[0,1],[1,2],[2,3],[3,4],[4,5],[5,0],[1,4]],
	"edges_assignment": ["B","B","B","B","B","B","V"],
	"faces_vertices": [[0,1,4,5],[1,2,3,4]],
	"file_frames": [{
		"frame_classes": ["foldedForm"],
		"frame_parent": 0,
		"frame_inherit": true,
		"vertices_coords": [
			[0,0],
			[0.6,0],
			[0.2307692307692307,-0.15384615384615383],
			[-0.15384615384615388,0.7692307692307692],
			[0.4,1],
			[0,1]
		],
		"faceOrders": [
			[0,1,1]
		]
	}]
}
```

### CODE REVIEW

**Comment by origamimagiro** [comment]
Nice catch! Unfortunately, this is a bigger issue than just a rendering problem (because normal direction is defined by winding of the face, rendering it upside-down should still be consistent). It seems that flat-folder did not comply with the FOLD spec in how it interpreted mountains and valleys! 

Previously, flat-folder associated the color-side winding with the normal direction of the face, but interpretted valleys and mountains as viewed from the white side (a mountain brings face normals toward each other). However, the FOLD spec says "For orientable manifolds, a valley fold points the two face normals toward each other, while a mountain fold makes them point away from each other", which is the opposite of what is flat-folder was doing. Since flat-folder shows the white side of the crease pattern (coordinates should be flipped), it also needs to flip the crease assignments displayed in the crease pattern rendering. Then the solver was fixed by just flipping the interpretation of order implied by crease assignment.

Thanks! This was something that was bugging me for a while (rendering different sides than other programs), but I didn't understand the problem until you brought it up!

**Comment by robbykraft** [comment]
tbh the decision to reverse all crease directions on import was surprising.

- it definitely adds a layer of abstraction away from the crease pattern provided. and imo, adds a layer of confusion.
- i thought the solution i provided solved everything, and maintained an unaltered crease pattern import, am i missing something?

> (because normal direction is defined by winding of the face, rendering it upside-down should still be consistent)

i almost took issue with this statement, but i'm guessing by "consistent", you mean consistent within your program only, right? we agree that this would not be consistent with the FOLD spec, right? (if not, maybe this is the misunderstanding)

**Comment by origamimagiro** [comment]
I'm not reversing all the crease directions on import. The crease directions are the same as in the file. FOLD spec assumes crease assignment as seen from the color side (direction of positive face normals). Flat-folder displays the crease pattern from the white side (direction of negative face normals), so it is natural that the crease assignment is reversed. Of course, one could render the color side instead, but this program chooses to show the crease pattern from the white side. 

I think we may be speaking past each other. There was a fundamental flaw with flat-folder not adhering to FOLD spec which occurred when processing crease assignment (thank you for finding!). FOLD spec does not make a distinction between white side and color side, but it does make a distinction between face normal direction. Your solution fixed the FOLD spec problem by flipping the output further down the processing pipeline, but the solver was still solving the assignment-reversed crease pattern. Additionally, your solution flips the orientation of the crease pattern to the color side (counter-clockwise orientation) while still coloring the crease pattern white, which would be inconsistent with flat-folder's perspective that positive normals are toward the colored side. 

> i almost took issue with this statement, but i'm guessing by "consistent", you mean consistent within your program only, right? we agree that this would not be consistent with the FOLD spec, right? (if not, maybe this is the misunderstanding)

I don't understand this statement. If you view the crease pattern from the color side (direction of positive face normal), all the assignments are as in the file. If you view the crease pattern from the white side (direction of negative face normal), all the assignments will be seen reversed. There is nothing inconsistent about this with respect to FOLD format. I am just rendering FOLD spec "M" edges as blue when seen from the white side and "V" edges as red when seen from the white side.

**Comment by origamimagiro** [comment]
After thinking about this more, there is actually a much bigger issue with flat-folder crease pattern import that needs to be addressed. Vertex coordinates are always provided in an $\hat{x}\hat{y}$ coordinate system, but there is an arbitrary choice for whether face normals should point in the direction $\hat{z} = \hat{x}\times \hat{y}$ or in the direction $-\hat{z}$, and either could be valid. 

While the current "fix" works for FOLD format crease patterns whose face normals point in the direction $\hat{z}$ direction, it does not work for when face normals point in the direction $-\hat{z}$. If you reverse the order of the arrays in `faces_vertices` in your (or any) example, it won't load correctly into flat-folder, even though it would be a valid FOLD format file and should be loaded. So we should handle that case when importing a FOLD file containing `faces_vertices`, and allow a user to select the face normal direction for an input crease pattern without face information (SVG, OPX, CP, FOLD without `faces_vertices`).

**Pull request closed without merging**
